#!/bin/bash

adb forward tcp:8080 tcp:8080

sudo modprobe v4l2loopback video_nr=4 'card_label=ipcam'

ffmpeg -i http://127.0.0.1:8080/video -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video4 
