#!/bin/bash

PROTOCOL=https
IP_ADDRESS=127.0.0.1
PORT=8080
ENDPOINT=video

if ! command -v adb &> /dev/null
then
    echo "adb is not installed!"
    exit
fi

if ! command -v mpv &> /dev/null
then
    echo "mpv is not installed!"
    exit
fi

echo "waiting for the device to show up via adb"
adb wait-for-usb-device

adb forward tcp:$PORT tcp:$PORT

echo "================================================================"
echo "If you want to control the resolution, focus, ISO and etc, visit $PROTOCOL://$IP_ADDRESS:$PORT/"
echo "================================================================"

mpv "$PROTOCOL://$IP_ADDRESS:$PORT/$ENDPOINT" --no-cache --untimed --no-demuxer-thread --video-sync=audio --vd-lavc-threads=1
